POST http://localhost:8081/wotinfo
Content-Type: application/json

{
   "data":{
      "serviceUri": "/plug06",
      "metadata":{
        "additionalProp1": "building01.floor02.room01.plug.01"
      },
      "property": "PoweredOn",
      "value": true
   }
}